# Generated by Django 4.2.3 on 2023-07-12 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='actions',
            old_name='cost',
            new_name='action_cost',
        ),
        migrations.RenameField(
            model_name='actions',
            old_name='name',
            new_name='action_name',
        ),
        migrations.RenameField(
            model_name='decorationzone',
            old_name='cost',
            new_name='zone_cost',
        ),
        migrations.RenameField(
            model_name='decorationzone',
            old_name='name',
            new_name='zone_name',
        ),
    ]
