# Generated by Django 4.2.3 on 2023-07-20 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_terms_way'),
    ]

    operations = [
        migrations.AlterField(
            model_name='terms',
            name='term_cost',
            field=models.FloatField(default=1),
        ),
        migrations.AlterField(
            model_name='way',
            name='way_cost',
            field=models.FloatField(default=1),
        ),
    ]
