# Generated by Django 4.2.3 on 2023-07-20 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_alter_terms_term_cost_alter_way_way_cost'),
    ]

    operations = [
        migrations.CreateModel(
            name='Selectio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('way_name', models.CharField(max_length=100)),
                ('way_cost', models.FloatField(default=1)),
            ],
        ),
    ]
