# Generated by Django 4.2.3 on 2023-07-20 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_selectio'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Selectio',
            new_name='Selection',
        ),
    ]
